# Generated by Django 4.2.5 on 2023-10-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stand', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stand',
        ),
    ]
